In [3]:
import numpy as np

<hr>

# Punto 1

In [8]:
w = np.array([[0.5],[-0.8]])
b = -1.23

x = np.array([[0.0], [1.0]])
y = 3.4

a = np.dot(w.T,x)+b

#descenso del gradiente
dw = (a-y)*x
db = (a-y)

learning_rate = 0.5

w_actualizado = w - learning_rate*dw
b_actualizado = b - learning_rate*db

print("Parametros actualizados: ",w_actualizado,b_actualizado)

('Parametros actualizados: ', array([[0.5  ],
       [1.915]]), array([[1.485]]))


In [140]:
#Verifiquemos que el error sea menor con los parametros actualizados
a1 = np.dot(w.T,x)+b
a2 = np.dot(w_actualizado.T,x)+b_actualizado

error1 = 1./2.*(a1-y)**2
error2 = 1./2.*(a2-y)**2

print("Errores antes y despues de la actualizacion: ", error1, error2)

('Errores antes y despues de la actualizacion: ', array([[14.74245]]), array([[9.86076132e-32]]))


<hr>

# Punto 2

In [141]:
def logloss(a, y):
    return -(y*np.log(a)+(1-y)*np.log(1-a))

def sigmoid(z):
    return 1. / (1. + np.exp(-z))

In [142]:
z = np.dot(w.T,x)+b
a = sigmoid(z)

y = 1.0

print("Valor del error logistico: ", logloss(a,y))

('Valor del error logistico: ', array([[2.15339881]]))


<hr>

# Punto 3

Dimensiones de los parametros $W$ y $b$:

<center><font size="5">

$W^{1}_{4 \times 3}, W^{2}_{2 \times 4}, W^{3}_{3 \times 2}, W^{4}_{5 \times 3}, W^{5}_{1 \times 5}$

<br>
<br>

$b^{1}_{4 \times 1}, b^{1}_{2 \times 1}, b^{1}_{3 \times 1}, b^{1}_{5 \times 1}, b^{1}_{1 \times 1}$

</font></center>

<hr>

# Punto 4

<img src="RNA.png" width="400">

<hr>

# Punto 5

In [155]:
W1 = np.random.random([4,3])
W2 = np.random.random([2,4])
W3 = np.random.random([3,2])
W4 = np.random.random([5,3])
W5 = np.random.random([1,5])

b1 = np.zeros([4,1])
b2 = np.zeros([2,1])
b3 = np.zeros([3,1])
b4 = np.zeros([5,1])
b5 = 0

In [156]:
nx = 3
m = 3

X = np.random.random([nx,m])
print(X)

[[0.15423724 0.17687794 0.88100883]
 [0.65805858 0.79097866 0.89643006]
 [0.35134163 0.02186133 0.12720672]]


In [157]:
#Forward Propagation
Z1 = np.dot(W1, X) + b1
A1 = sigmoid(Z1)

Z2 = np.dot(W2, A1) + b2
A2 = sigmoid(Z2)

Z3 = np.dot(W3, A2) + b3
A3 = sigmoid(Z3)

Z4 = np.dot(W4, A3) + b4
A4 = sigmoid(Z4)

Z5 = np.dot(W5, A4) + b5
A5 = sigmoid(Z5)

print(A5)

[[0.84724114 0.84714415 0.8477757 ]]


In [119]:
np.random.randint??