In [4]:
import numpy as np
#from __future__ import division

In [7]:
def accuracy(pred, Y):
    n = len(Y)
    correctly_classified = np.count_nonzero(Y == pred)
    
    return correctly_classified / float(n)

In [8]:
Y = np.array([0,0,0,1,1,1])
pred = np.array([1,0,0,0,1,1])

print(accuracy(pred, Y))

0.666666666667


In [10]:
from sklearn.datasets import load_iris

dataset = load_iris()
X, Y = dataset.data, dataset.target

In [13]:
from sklearn.neighbors import KNeighborsClassifier

In [14]:
model = KNeighborsClassifier(n_neighbors=3)

In [15]:
model.fit(X, Y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=3, p=2,
           weights='uniform')

In [17]:
preds = model.predict(X)

In [19]:
print(accuracy(preds, Y))

0.96


In [20]:
from sklearn.metrics import accuracy_score

In [21]:
print(accuracy_score(preds, Y))

0.96


In [25]:
n = np.shape(X)[0]
train_len = int(n * 0.7)

X_train, Y_train = X[0:train_len], Y[0:train_len]
X_test, Y_test = X[train_len:], Y[train_len:]

In [29]:
model.fit(X_train, Y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=3, p=2,
           weights='uniform')

In [30]:
preds = model.predict(X_test)
print(accuracy_score(preds, Y_test))

0.6222222222222222


In [31]:
Y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [54]:
indices = np.arange(0,149,1)
perm_index = np.random.permutation(indices)

In [55]:
X_train, Y_train = X[perm_index[0:train_len]], Y[perm_index[0:train_len]]
X_test, Y_test = X[perm_index[train_len:]], Y[perm_index[train_len:]]

In [41]:
Y_train

array([2, 0, 2, 1, 1, 0, 0, 1, 2, 2, 1, 1, 0, 2, 0, 0, 0, 1, 0, 1, 1, 0,
       1, 2, 2, 1, 2, 0, 2, 2, 1, 0, 1, 1, 0, 2, 0, 0, 1, 2, 0, 0, 0, 0,
       1, 2, 2, 2, 1, 1, 2, 1, 1, 1, 1, 1, 0, 2, 0, 0, 0, 2, 2, 1, 1, 1,
       0, 0, 0, 1, 2, 0, 2, 2, 1, 2, 1, 2, 1, 1, 0, 1, 2, 2, 2, 2, 0, 0,
       2, 2, 2, 1, 2, 1, 2, 0, 0, 1, 2, 1, 1, 0, 1, 2, 0])

In [56]:
model = KNeighborsClassifier(n_neighbors=3)
model.fit(X_train, Y_train)
preds = model.predict(X_test)
print(accuracy_score(preds, Y_test))

0.8863636363636364


In [57]:
sum_accuracy = 0

for i in range(10):
    indices = np.arange(0,149,1)
    perm_index = np.random.permutation(indices)
    X_train, Y_train = X[perm_index[0:train_len]], Y[perm_index[0:train_len]]
    X_test, Y_test = X[perm_index[train_len:]], Y[perm_index[train_len:]]
    model = KNeighborsClassifier(n_neighbors=3)
    model.fit(X_train, Y_train)
    preds = model.predict(X_test)
    sum_accuracy += accuracy_score(preds, Y_test)

print(sum_accuracy / 10)

0.9704545454545455


In [58]:
from sklearn.model_selection import KFold

In [78]:
kfolds = KFold(n_splits=20)
kfolds.get_n_splits(X)

sum_accuracy = 0

for train_index, test_index in kfolds.split(X):
    #print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = X[train_index], X[test_index]
    Y_train, Y_test = Y[train_index], Y[test_index]
    
    model = KNeighborsClassifier(n_neighbors=3)
    model.fit(X_train, Y_train)
    preds = model.predict(X_test)
    sum_accuracy += accuracy_score(preds, Y_test)

print(sum_accuracy / 20)

0.9589285714285716


In [71]:
??KFold

In [80]:
from sklearn.metrics import confusion_matrix

model = KNeighborsClassifier(n_neighbors=3)
model.fit(X, Y)
preds = model.predict(X)
#print(accuracy_score(preds, Y_test))
print(confusion_matrix(preds, Y))

[[50  0  0]
 [ 0 47  3]
 [ 0  3 47]]
